# Generated by Django 3.0.7 on 2020-06-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_myplaylistmusic'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='album',
            field=models.ManyToManyField(through='account.MyFavoriteAlbum', to='music.Album'),
        ),
        migrations.AlterField(
            model_name='user',
            name='artist',
            field=models.ManyToManyField(through='account.MyFavoriteArtist', to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='music',
            field=models.ManyToManyField(through='account.MyFavoriteMusic', to='music.Music'),
        ),
        migrations.AlterModelTable(
            name='myfavoritemusic',
            table='myfavorite_music',
        ),
    ]
