# Generated by Django 3.0.7 on 2020-06-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200611_0212'),
        ('account', '0002_auto_20200611_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='album',
            field=models.ManyToManyField(through='account.MyFavoriteAlbum', to='music.Album'),
        ),
        migrations.AlterField(
            model_name='user',
            name='artist',
            field=models.ManyToManyField(through='account.MyFavoriteArtist', to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='music',
            field=models.ManyToManyField(through='account.MyFavoriteMusic', to='music.Music'),
        ),
    ]
