# Generated by Django 3.0.7 on 2020-06-12 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=2000)),
                ('description', models.TextField()),
                ('release_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('debut_date', models.CharField(max_length=50, null=True)),
                ('image_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sound', models.URLField(max_length=2000)),
                ('playtime', models.TimeField(null=True)),
                ('play_count', models.IntegerField(default=0, null=True)),
                ('lyrics', models.TextField()),
                ('is_title', models.BooleanField()),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Album')),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'staff_types',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'themes',
            },
        ),
        migrations.CreateModel(
            name='StaffStaffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Staff')),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.StaffType')),
            ],
            options={
                'db_table': 'staff_staff_types',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.ManyToManyField(through='music.StaffStaffType', to='music.StaffType'),
        ),
        migrations.CreateModel(
            name='MyplaylistMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music')),
                ('myplaylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MyPlaylist')),
            ],
            options={
                'db_table': 'myplaylist_music',
            },
        ),
        migrations.CreateModel(
            name='MusicArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music')),
            ],
            options={
                'db_table': 'music_artists',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(through='music.MusicArtist', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='music',
            name='myplaylist',
            field=models.ManyToManyField(through='music.MyplaylistMusic', to='account.MyPlaylist'),
        ),
        migrations.AddField(
            model_name='music',
            name='staff',
            field=models.ManyToManyField(through='music.StaffStaffType', to='music.Staff'),
        ),
        migrations.CreateModel(
            name='DjStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Music')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Theme')),
            ],
            options={
                'db_table': 'dj_stations',
            },
        ),
        migrations.CreateModel(
            name='ArtistGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Genre')),
            ],
            options={
                'db_table': 'artist_genres',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(through='music.ArtistGenre', to='music.Genre'),
        ),
    ]
