# Generated by Django 3.0.7 on 2020-06-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyplaylistMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music')),
                ('myplaylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Myplaylist')),
            ],
            options={
                'db_table': 'myplaylist_musics',
            },
        ),
    ]
