# Generated by Django 3.0.7 on 2020-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffstafftype',
            name='music',
        ),
        migrations.RemoveField(
            model_name='staffstafftype',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffstafftype',
            name='staff_type',
        ),
        migrations.RemoveField(
            model_name='music',
            name='staff',
        ),
        migrations.AddField(
            model_name='music',
            name='arranger',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='composer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='writer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffStaffType',
        ),
        migrations.DeleteModel(
            name='StaffType',
        ),
    ]
