# Generated by Django 3.0.7 on 2020-06-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200611_0212'),
        ('music', '0002_myplaylistmusic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplaylistmusic',
            name='myplaylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MyPlaylist'),
        ),
        migrations.AlterModelTable(
            name='music',
            table='music',
        ),
    ]
