# Generated by Django 3.0.7 on 2020-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200612_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='arranger',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='composer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='writer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
