# Generated by Django 3.0.7 on 2020-06-11 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200611_0357'),
        ('music', '0003_auto_20200611_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplaylistmusic',
            name='myplaylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MyPlaylist'),
        ),
        migrations.AlterModelTable(
            name='myplaylistmusic',
            table='myplaylist_music',
        ),
    ]
