# Generated by Django 3.0.7 on 2020-06-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200611_0449'),
        ('music', '0004_auto_20200611_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(through='music.ArtistGenre', to='music.Genre'),
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(through='music.MusicArtist', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='music',
            name='myplaylist',
            field=models.ManyToManyField(through='music.MyplaylistMusic', to='account.MyPlaylist'),
        ),
        migrations.AddField(
            model_name='music',
            name='staff',
            field=models.ManyToManyField(through='music.MusicStaff', to='music.Staff'),
        ),
        migrations.AlterField(
            model_name='myplaylistmusic',
            name='myplaylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MyPlaylist'),
        ),
    ]
