# Generated by Django 3.0.7 on 2020-06-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200611_0526'),
        ('music', '0005_auto_20200611_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
        migrations.AlterField(
            model_name='music',
            name='myplaylist',
            field=models.ManyToManyField(through='music.MyplaylistMusic', to='account.MyPlaylist'),
        ),
        migrations.AlterField(
            model_name='myplaylistmusic',
            name='myplaylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MyPlaylist'),
        ),
    ]
